#!/bin/bash

lfs_dirs() {
	mkdir -pv $LFS/dev
	mknod -m 600 $LFS/dev/console c 5 1 || true
	mknod -m 666 $LFS/dev/null c 1 3 || true

	mkdir -pv $LFS/bin $LFS/usr/{lib,bin} $LFS/etc || true
	ln -svf /tools/bin/{bash,cat,chmod,dd,echo,ln,mkdir,pwd,rm,stty,touch} $LFS/bin
	ln -svf /tools/bin/{env,install,perl,printf}         $LFS/usr/bin
	ln -svf /tools/lib/libgcc_s.so{,.1}                  $LFS/usr/lib
	ln -svf /tools/lib/libstdc++.{a,so{,.6}}             $LFS/usr/lib

	ln -svf bash $LFS/bin/sh

	ln -svf /proc/self/mounts $LFS/etc/mtab

cat > $LFS/etc/passwd << "EOF"
root:x:0:0:root:/root:/bin/bash
bin:x:1:1:bin:/dev/null:/bin/false
daemon:x:6:6:Daemon User:/dev/null:/bin/false
messagebus:x:18:18:D-Bus Message Daemon User:/var/run/dbus:/bin/false
systemd-bus-proxy:x:72:72:systemd Bus Proxy:/:/bin/false
systemd-journal-gateway:x:73:73:systemd Journal Gateway:/:/bin/false
systemd-journal-remote:x:74:74:systemd Journal Remote:/:/bin/false
systemd-journal-upload:x:75:75:systemd Journal Upload:/:/bin/false
systemd-network:x:76:76:systemd Network Management:/:/bin/false
systemd-resolve:x:77:77:systemd Resolver:/:/bin/false
systemd-timesync:x:78:78:systemd Time Synchronization:/:/bin/false
systemd-coredump:x:79:79:systemd Core Dumper:/:/bin/false
nobody:x:99:99:Unprivileged User:/dev/null:/bin/false
EOF

cat > $LFS/etc/group << "EOF"
root:x:0:
bin:x:1:daemon
sys:x:2:
kmem:x:3:
tape:x:4:
tty:x:5:
daemon:x:6:
floppy:x:7:
disk:x:8:
lp:x:9:
dialout:x:10:
audio:x:11:
video:x:12:
utmp:x:13:
usb:x:14:
cdrom:x:15:
adm:x:16:
messagebus:x:18:
systemd-journal:x:23:
input:x:24:
mail:x:34:
kvm:x:61:
systemd-bus-proxy:x:72:
systemd-journal-gateway:x:73:
systemd-journal-remote:x:74:
systemd-journal-upload:x:75:
systemd-network:x:76:
systemd-resolve:x:77:
systemd-timesync:x:78:
systemd-coredump:x:79:
wheel:x:97:
nogroup:x:99:
users:x:999:
EOF

	# pkgutils
	mkdir -p $LFS/var/lib/pkg/{pkg,src,work}
	touch $LFS/var/lib/pkg/db
}

mount_pseudo() {
	mkdir -p $LFS/{dev,run,proc,sys}
	mount --bind /dev $LFS/dev
	mount -t devpts devpts $LFS/dev/pts -o gid=5,mode=620
	mount -t proc proc $LFS/proc
	mount -t sysfs sysfs $LFS/sys
	mount -t tmpfs tmpfs $LFS/run
	if [ -h $LFS/dev/shm ]; then
	  mkdir -p $LFS/$(readlink $LFS/dev/shm)
	fi
}

umount_pseudo() {
	unmount $LFS/dev/pts
	unmount $LFS/dev
	unmount $LFS/run
	unmount $LFS/proc
	unmount $LFS/sys
}

mountbind_srcpkg() {
	mount --bind $SRCDIR $LFS/var/lib/pkg/src
	mount --bind $PKGDIR $LFS/var/lib/pkg/pkg
}

unmountbind_srcpkg() {
	unmount $LFS/var/lib/pkg/src
	unmount $LFS/var/lib/pkg/pkg
}

unmount() {
	while true; do
		mountpoint -q $1 || break
		umount $1 2>/dev/null
	done
}

runinchroot() {
	pushd $LFS &>/dev/null
	mount_pseudo
	mountbind_srcpkg
	cp -L /etc/resolv.conf $LFS/etc/
	chroot "$LFS" $ENVLFS -i \
	    HOME=/root                  \
	    TERM="$TERM"                \
	    PS1="\[\e[37;40m\][\[\e[31;40m\](lfs chroot) \[\e[32;40m\]\u:\[\e[36;40m\]\w \[\e[0m\]]\\$ " \
	    PATH=/bin:/usr/bin:/sbin:/usr/sbin:/tools/bin $@
	retval=$?
	unmountbind_srcpkg
	umount_pseudo
	popd &>/dev/null
	return $retval
}

interrupted() {
	die "script $(basename $0) aborted!"
}

die() {
	[ "$@" ] && printerror $@
	unmountbind_srcpkg
	umount_pseudo
	exit 1
}

printerror() {
	echo -e "ERROR: $@"
}

trap "interrupted" SIGHUP SIGINT SIGQUIT SIGTERM

if [ $(id -u) != 0 ]; then
	echo "$0 script need to run as root!"
	exit 1
fi

CWD=$PWD

if [ -f $CWD/config ]; then
	source $CWD/config
fi

MAKEFLAGS="${MAKEFLAGS:--j$(nproc)}"
LFS="${LFS:-/mnt/lfs}"
PKGDIR="${PKGDIR:-$CWD/pkg}"
#SRCDIR="${SRCDIR:-$CWD/src}"
SRCDIR="${SRCDIR:-/sources}"
WORKDIR="${WORKDIR:-/tmp}"

if [ -x $LFS/usr/bin/env ]; then
	ENVLFS=/usr/bin/env
else
	ENVLFS=/tools/bin/env
fi

PKGS="filesystem linux-api-headers man-pages glibc tzdata zlib bzip2 xz file readline m4 bc binutils gmp mpfr mpc attr acl pam shadow gcc pkg-config ncurses libcap sed psmisc iana-etc bison flex grep bash libtool gdbm gperf expat inetutils perl perl-xml-parser intltool autoconf automake kmod gettext elfutils libffi openssl python3 ninja meson coreutils check diffutils gawk findutils groff less gzip zstd iproute2 kbd libpipeline make patch man-db tar texinfo vim lz4 systemd dbus procps-ng util-linux e2fsprogs linux-firmware libarchive which cpio
libxml2 sgml-common unzip docbook-xml docbook-xsl libxslt asciidoc dracut linux  libtasn1  p11-kit  ca-certificates wget pkgutils"

# libnl dhcpcd wpa_supplicant lzo squashfs-tools popt efivar pciutils efibootmgr libpng freetype2 dosfstools grub-efi curl ports httpup gpm libevent links

if [ ! -f $LFS/var/lib/pkg/db ]; then
	lfs_dirs
fi

rm -fr $LFS/usr/ports
mkdir -p $LFS/usr/ports/
echo "==> Copying ports"
cp -Ra ports/* $LFS/usr/ports/

for pkg in $PKGS; do
	case $pkg in
		filesystem|gcc|bash|perl|coreutils) runinchroot pkgin -i -ic $pkg || die;;
		*) runinchroot pkgin -i $pkg || die;;
	esac
done

exit 0
