#!/bin/sh

systemd-machine-id-setup

systemctl preset-all

systemctl disable systemd-time-wait-sync.service

cat >> /etc/pam.d/system-session << "EOF"


# Begin Systemd addition
    
session  required    pam_loginuid.so
session  optional    pam_systemd.so

# End Systemd addition
EOF
